### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maxnussbaum** [findgoodfood-proj/FindGoodFood#6]
- [ ] CSS for Dashboard
- [ ] CSS for Dashboard and Homepage Buttons
- [x] Views for both Results pages
- [x] Views for Restaurant page
- [x] Controller for Restaurants
- [x] Controller for Ratings
- [x] Controller for Food

**Comment by hb-robo** [comment]
Everything but the dashboard is completed.
